exParcial/exParcial/urls.py
from django.contrib import admin
from django.urls import path,include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('wikiApp.urls'))
    
   # path('vistaPrincipal', include('wikiApp.urls')),  # Asegúrate de que tu app esté correctamente incluida.
   # path('', lambda request: redirect('vistaPrincipal', permanent=True)),  # Redirigir raíz a /vistaPrincipal

]

exParcial/wikiApp/urls.py
from django.urls import path
from . import views

app_name= 'wikiApp' 

urlpatterns = [
    
     #path('',views.hola,name='hola'),
        
    #path('',views.layout,name='layout'),

     path('',views.vistaPrincipal,name='vistaPrincipal'),
           
     path('vistaPrincipal', views.mostrar_temas_y_articulos, name='mostrar_temas_y_articulos'),
     
     path('vistaBusqueda',views.vistaBusqueda,name='vistaBusqueda'),

     #path('vistaPrincipal', views.vistaBusqueda, name='vistaBusqueda'),

     path('vistaCrearNuevotema',views.vistaCrearNuevotema,name='vistaCrearNuevotema'),

     path('vistaCrearNuevoArticulo',views.vistaCrearNuevoArticulo,name='vistaCrearNuevoArticulo'),

     path('vistaArticulos',views.vistaArticulos,name='vistaArticulos'),

 
]

exParcial/wikiApp/models.py
from django.db import models

# Create your models here.

class temaWiki(models.Model):
    nombre = models.CharField(max_length=128, null = True, blank=True,)
    descripcion = models.CharField(max_length=512, null = True, blank=True,)

class articuloWiki(models.Model):
    titulo = models.CharField(max_length=128, null = True, blank=True,)
    contenido = models.CharField(max_length=1024, null = True, blank=True,)
    temaRelacionado = models.ForeignKey(temaWiki, on_delete=models.CASCADE, related_name='articulos')

exParcial/wikiApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse

listaTemas = [
    ['Frameworks','Django y Flask son los principales frameworks para crear aplicaciones web con Python de forma rápida y eficiente'],
    ['Backend','Python se usa para construir la lógica del servidor, interactuando con bases de datos y creando APIs.'],
    ['Bases de Datos','Python se conecta a diferentes tipos de bases de datos (SQL y NoSQL) para almacenar y gestionar información.']
]

listaArticulos = [
    ['Artículo 1.1','Frameworks','Contenido del Artículo 1.1'],    
    ['Artículo 1.2','Frameworks','Contenido del Artículo 1.2'],    
    ['Artículo 2.1','Backend','Contenido del Artículo 2.1'],    
    ['Artículo 3.1','Bases de Datos','Contenido del Artículo 3.1'],   
    ['Artículo 3.2','Bases de Datos','Contenido del Artículo 3.2']   
]


# Create your views here.
def hola(request):
    return HttpResponse("Bienvenidos a mi Web- Gestión de Temas y Artículos")

def layout(request):
    return render (request,'layout.html', {
        'listaTemas':listaTemas,
        'listaArticulos':listaArticulos, 
    })

def vistaPrincipal(request):
    return render (request,'vistaPrincipal.html',{
        'listaTemas': listaTemas,
        'listaArticulos':listaArticulos, 
    })

def vistaCrearNuevotema(request):
    if request.method =='POST':
        nombreTema = request.POST.get('nombreTema')
        descripcionTema = request.POST.get('descripcionTema')
        
        print(request.POST)

        print(nombreTema)
        print(descripcionTema)

        listaTemas.append([nombreTema,descripcionTema])

        # return HttpResponseRedirect(reverse('wikiApp:vistaPrincipal'))
    return render (request,'vistaCrearNuevoTema.html', {
        'listaTemas':listaTemas,
         'listaArticulos':listaArticulos,
    })

def vistaCrearNuevoArticulo(request):
        
        tituloArticulo = None
        temaSeleccionado = None
        contenidoArticulo = None

        if request.method =='POST':

            tituloArticulo  = request.POST.get('tituloArticulo')
            temaSeleccionado = request.POST.get('temaSeleccionado')
            contenidoArticulo = request.POST.get('contenidoArticulo')
            
            print (request.POST)

            listaArticulos.append([tituloArticulo,temaSeleccionado,contenidoArticulo])
            
           # return HttpResponseRedirect(reverse('wikiApp:vistaArticulos'))

            return render (request,'vistaArticulos.html', {
            'listaArticulos':listaArticulos, 
            'listaTemas':listaTemas
            })
        return render (request,'vistaCrearNuevoArticulo.html', {
            'listaTemas':listaTemas
        })

def mostrar_temas_y_articulos(request):
        # Obtener el tema seleccionado desde los parámetros GET
        tema_seleccionado = request.GET.get('tema','Frameworks')
        
        # Filtrar los artículos según el tema seleccionado
        if tema_seleccionado:
            articulos_filtrados = [articulo for articulo in listaArticulos if articulo[1] == tema_seleccionado]
        else:
            articulos_filtrados = []

        context = {
            'listaTemas': listaTemas,
            'listaArticulos': articulos_filtrados,
            'tema_seleccionado': tema_seleccionado,
        }

        # Pasar las listas a la plantilla
        return render(request, 'vistaPrincipal.html', context)

def vistaArticulos(request):
    return render (request,'vistaArticulos.html', {
         'listaTemas': listaTemas,
         'listaArticulos':listaArticulos,
    })

def vistaBusqueda(request):

    # Obtiene el término de búsqueda desde el formulario GET
    query = request.GET.get('q', '')
    resultados = []

    if query:
    # Filtra los artículos que contienen el término de búsqueda en cualquier campo
     resultados = [art for art in listaArticulos if query.lower() in art[0].lower() or query.lower() in art[1].lower() or query.lower() in art[2].lower()]

    return render (request, 'vistaBusqueda.html', {
        'resultados': resultados,
        'query': query,
        'listaTemas':listaTemas,
    })

exParcial/wikiApp/templates/layout.html
<!DOCTYPE html>
<html lang="es">
<head>
  
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title> {% block titulo %} {% endblock %}</title>

  <!-- Enlace a Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  
</head>
<body>
  <div class="container-fluid">
        <h1 class="my-4 text-center">Gestión de Temas y Artículos</h1>
        <div class="row">
            <!-- Panel izquierdo -->
            <div class="col-md-3 bg-light p-3 border">
                    <!-- Botón Home -->
                    <div class="d-grid mb-3">
                       <!-- Botón Home con JavaScript -->
                       <button class="btn btn-dark" id="btnHome" onclick="window.location.href='{% url 'wikiApp:vistaPrincipal' %}'">Home</button>
                         <!-- <a class="btn btn-dark" href="{% url 'wikiApp:vistaPrincipal' %}" >Home</a> -->
                    </div>

                    <!-- Barra de búsqueda -->
                    <div class="d-grid gap-2 mb-4">
                      <form method="get" action="{% url 'wikiApp:vistaBusqueda' %}">
                        <input type="text" name="q" class="form-control" placeholder="Buscar artículo..." value="{{ query }}">
                        <button type="submit"  class="btn btn-success" class="form-control" >Buscar</button>
                      </form>
                    </div>

                    <!-- Botones de acciones -->
                    <div class="d-grid gap-2 mb-4">
                        <button class="btn btn-primary" onclick="window.location.href='{% url 'wikiApp:vistaCrearNuevotema' %}'"  >Crear nuevo tema</button>
                        <button class="btn btn-success" onclick="window.location.href='{% url 'wikiApp:vistaCrearNuevoArticulo' %}'" >Crear nuevo artículo</button>
                        <button class="btn btn-success" onclick="window.location.href='{% url 'wikiApp:vistaArticulos' %}'"  >Vista Articulos</button>
                       
                    </div>

                    <h3 class="my-4 text-center" >Lista de Temas</h3>

                    {% block listaTemasRegistrados %}
                          <ol>
                            {% for temainfo in listaTemas %}
                              <li>
                                  <ul class="list-group mb-3">
                                      <li class="list-group-item">
                                          <a href="vistaPrincipal?tema={{ temainfo.0 }}" class="text-decoration-none">
                                              Tema: {{ temainfo.0 }}
                                          </a>
                                      </li>
                                      <li class="list-group-item">
                                          Descripción: {{ temainfo.1 }}
                                      </li>
                                  </ul>
                              </li>
                            {% endfor %}
                          </ol>
                    {% endblock %} 

            </div>

            <!-- Área derecha en blanco -->
            <div class="col-md-9 p-3">
                <!-- Este espacio se puede utilizar para mostrar contenido dinámico -->
                <!-- <h2>Área derecha en blanco</h2> -->
                {% block contenido %} 
                
                {% endblock %}
            </div>
      </div>
  </div>

  <!-- Enlace a Bootstrap JS (opcional si se requiere funcionalidad de JavaScript) -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

exParcial/wikiApp/templates/vistaArticulos.html
{% extends "layout.html" %}

{% block titulo %}

  Gestión de Temas y Artículos

{% endblock %}

{% block contenido %}

    <h3>Vista de lista de artículos:</h3>
      <ol>
        {% for Art in listaArticulos %}
          <li>
            <ul class="list-group mb-3">
                  <li class="list-group-item">
                      Articulo: {{ Art.0 }}
                  </li>
                  <li class="list-group-item">
                      Tema: {{ Art.1 }}
                  </li>
                  <li class="list-group-item">
                    Contenido: {{ Art.2 }}
                </li>
            </ul>
          </li>
        {% endfor %}
      </ol> 


{% endblock %}

exParcial/wikiApp/templates/vistaBusqueda.html
{% extends "layout.html" %}

{% block titulo %}

  Gestión de Temas y Artículos

{% endblock %}

{% block contenido %}

    <h5>Vista de búsqueda:</h5>

    
     {% if resultados %}
          <ol>
              {% for Articulo in resultados %}
                  <li>
                      <ul class="list-group mb-3">
                          <li class="list-group-item">
                              <strong>Artículo:</strong> {{ Articulo.0 }}
                          </li>
                          <li class="list-group-item">
                            <strong>Tema:</strong> {{ Articulo.1 }}
                        </li>
                          <li class="list-group-item">
                              <strong>Contenido:</strong> {{ Articulo.2 }}
                          </li>
                      </ul>
                  </li>
              {% endfor %}
          </ol>
          {% else %}
              <p>No hay artículos disponibles para el tema seleccionado.</p>
      {% endif %}
{% endblock %}

exParcial/wikiApp/templates/vistaCrearNuevoArticulo.html
{% extends "layout.html" %}

{% block titulo %}

  Gestión de Temas y Artículos

{% endblock %}

{% block contenido %}

  <h3>Vista crear nuevo Articulo :</h3>

      <form method="post" action="{% url 'wikiApp:vistaCrearNuevoArticulo' %}">
        {% csrf_token %}
        <div class="mb-3">
          <label for="tituloArticulo" class="form-label">Título del artículo</label>
          <input type="text" class="form-control" name="tituloArticulo" placeholder="Ingrese el título del artículo">
        </div>
        <div class="mb-3">
          <label for="temaSeleccionado" class="form-label">Seleccionar tema</label>
          <select class="form-select" name="temaSeleccionado">
            <option value="">Seleccione un tema</option>
            {% for temainfo in listaTemas %}
                <option value="{{ temainfo.0 }}">{{ temainfo.0 }}</option>
            {% endfor %}
          </select>
        </div>
        <div class="mb-3">
          <label for="contenidoArticulo" class="form-label">Contenido del artículo</label>
          <textarea class="form-control" name="contenidoArticulo" rows="6" placeholder="Ingrese el contenido del artículo"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
      </form>

{% endblock %}

exParcial/wikiApp/templates/vistaCrearNuevotema.html
{% extends "layout.html" %}

{% block titulo %}

  Gestión de Temas y Artículos

{% endblock %}

{% block contenido %}

 <!--Mostrar el formulario para crear un nuevo tema -->
  
 <h3>Vista Crear Nuevo Tema:</h3>

  <form method = "post" action="{% url 'wikiApp:vistaCrearNuevotema' %}" >

    {% csrf_token %}

    <div class="mb-3">
      <label for="nombreTema" class="form-label">Nombre del tema</label>
      <input type="text" class="form-control" name="nombreTema" placeholder="Ingrese el nombre del tema">
    </div>
    
    <div class="mb-3">
      <label for="descripcionTema" class="form-label">Descripción</label>
      <textarea class="form-control" name="descripcionTema" rows="4" placeholder="Ingrese la descripción del tema"></textarea>
    </div>

    <button type="submit" class="btn btn-primary" >Registrar</button>

  </form>   

{% endblock %}

exParcial/wikiApp/templates/vistaPrincipal.html
{% extends "layout.html" %}

{% block titulo %}

  Gestión de Temas y Artículos

{% endblock %}

{% block contenido %}
  
<!-- Artículos Filtrados (lado derecho) -->
                                
  {% if tema_seleccionado %}

      <h5>Artículos del Tema "{{ tema_seleccionado }}"</h5>

      {% if listaArticulos %}
          <ol>
              {% for Articulo in listaArticulos %}
                  <li>
                      <ul class="list-group mb-3">
                          <li class="list-group-item">
                              <strong>Artículo:</strong> {{ Articulo.0 }}
                          </li>
                          <li class="list-group-item">
                              <strong>Contenido:</strong> {{ Articulo.2 }}
                          </li>
                      </ul>
                  </li>
              {% endfor %}
          </ol>
      {% else %}
          <p>No hay artículos disponibles para el tema seleccionado.</p>
      {% endif %}
  {% else %}
      <h3>Selecciona un tema para ver los artículos:</h3>
  {% endif %}
  
{% endblock %}